# Generated by Django 2.0.6 on 2019-10-11 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('salary', models.FloatField()),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='self_app.Emp')),
            ],
            options={
                'db_table': 'emps',
            },
        ),
    ]
