# Generated by Django 2.0.6 on 2019-10-11 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='self_app.Spy')),
            ],
            options={
                'db_table': 'spies',
            },
        ),
    ]
