# Generated by Django 2.0.6 on 2019-10-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='students',
        ),
    ]
