# Generated by Django 2.0.6 on 2019-10-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relation_app', '0002_auto_20191010_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('buildtime', models.DateField()),
            ],
            options={
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_reason', models.CharField(max_length=30, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation_app.Community')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relation_app.Member')),
            ],
            options={
                'db_table': 'relations',
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='per',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='relation_app.Person'),
        ),
        migrations.AddField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='comms', through='relation_app.Relation', to='relation_app.Member'),
        ),
    ]
