# Generated by Django 2.0.6 on 2019-10-16 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学校名称')),
                ('address', models.CharField(max_length=50, verbose_name='地址')),
            ],
            options={
                'verbose_name': '学校模型',
                'verbose_name_plural': '学校模型',
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('sex', models.CharField(max_length=10, verbose_name='性别')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_perm_app.School', verbose_name='所在学校')),
            ],
            options={
                'verbose_name': '学生模型',
                'verbose_name_plural': '学生模型',
                'db_table': 'students',
            },
        ),
    ]
