# Generated by Django 2.0.6 on 2019-10-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_perm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('visit_vip', 'Can operate vip student'),), 'verbose_name': '学生模型', 'verbose_name_plural': '学生模型'},
        ),
    ]
